---
name: Terraform

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: fmt
          tf_actions_comment: true

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: latest
          tf_actions_subcommand: init
          tf_actions_comment: true
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        env:
          AWS_DEFAULT_REGION: eu-west-1
        with:
          tf_actions_version: latest
          tf_actions_subcommand: validate
          tf_actions_comment: true

  terraform-docs:
    runs-on: ubuntu-latest
    needs: [terraform-fmt, terraform-sec, terraform-validate]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update module usage docs and push any changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          args: '--sort-inputs-by-required'
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: 'terraform-docs: Update module usage'

  terraform-sec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.3
